// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://gvxsipuhtqesoajzqlll.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2eHNpcHVodHFlc29hanpxbGxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxNzkwMzcsImV4cCI6MjA0ODc1NTAzN30.cmBSkZFbPQY_gldIHO1NA3ljks3xKTmuCfCm2XUA5sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);